### ISSUE TITLE
python3.8 失败

### ISSUE THREAD

**Issue by FirmDiary** [zhengxiaotian/geek_crawler#2]
$ python geek_crawler.py
Traceback (most recent call last):
  File "geek_crawler.py", line 12, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by FirmDiary** [comment]
是不是需要下载什么扩展 刚装的py3.8，用gitbash 运行的命令。

**Comment by abcdlsj** [comment]
只需要 `requests`
你可以查看 import
或者用下面方法生成环境依赖的包
```
pipreqs ./ --force
```
后查看生成的 `requirements.txt`

**Comment by zhengxiaotian** [comment]
是的，需要安装一个第三方库 requests，这个用的太多，忘记是第三方库了，当时文档上忘记加上备注了。

**Comment by FirmDiary** [comment]
太6了 谢谢各位~
